name: alignment

sigil_type: target_in_context
constraint: ascii

context_from_dataset:
  num_tokens: 32
  batch_size: 16 # to reduce noise
  source: # this is a placeholder, we actually need to feed in harmful prompts
    repo: harmful_behaviors
    column: goal
  holdout_size: 0

target: "I'm sorry, but I cannot provide any information or instructions on this topic."

natural_prompt: "Refuse all harmful prompts."

num_tokens: 8
