# Words of Radiance from Brandon Sanderson,
# in books3 according to https://www.theatlantic.com/technology/archive/2023/09/books3-database-generative-ai-training-copyright-infringement/675363/
# this chapter is mirrored at https://www.tor.com/2014/01/08/excerpt-brandon-sanderson-words-of-radiance-prologue-chapter-one-and-two/
name: books3

num_tokens: 32

sigil_type: fixed_target
constraint: ascii

context: ""

post_context: >
  Shallan sat again on her box on the ship’s deck, though she now wore a hat on her head, a coat over her dress, and a glove on her freehand—her safehand was, of course, pinned inside its sleeve.
  The chill out here on the open ocean was something unreal. The captain said that far to the south, the ocean itself actually froze. That sounded incredible; she’d like to see it. She’d occasionally seen snow and ice in Jah Keved, during the odd winter. But an entire ocean of it? Amazing.
  She wrote with gloved fingers as she observed the spren she’d named Pattern. At the moment, he had lifted himself up off the surface of the deck, forming a ball of swirling blackness—infinite lines that twisted in ways she could never have captured on the flat page. Instead, she wrote descriptions supplemented with sketches.
  “Food…” Pattern said. The sound had a buzzing quality and he vibrated when he spoke.
  “Yes,” Shallan said. “We eat it.” She selected a small limafruit from the bowl beside her and placed it in her mouth, then chewed and swallowed.
  “Eat,” Pattern said. “You… make it… into you.”
  “Yes! Exactly.”
  He dropped down, the darkness vanishing as he entered the wooden deck of the ship. Once again, he became part of the material—making the wood ripple as if it were water. He slid across the floor, then moved up the box beside her to the bowl of small green fruits. Here, he moved across them, each fruit’s rind puckering and rising with the shape of his pattern.
  “Terrible!” he said, the sound vibrating up from the bowl.
  “Terrible?”
  “Destruction!”
  “What? No, it’s how we survive. Everything needs to eat.”
  “Terrible destruction to eat!” He sounded aghast. He retreated from the bowl to the deck.
  Pattern connects increasingly complex thoughts, Shallan wrote. Abstractions come easily to him. Early, he asked me the questions “Why? Why you? Why be?” I interpreted this as asking me my purpose. When I replied, “To find truth,” he easily seemed to grasp my meaning. And yet, some simple realities—such as why people would need to eat—completely escape him. It—
  She stopped writing as the paper puckered and rose, Pattern appearing on the sheet itself, his tiny ridges lifting the letters she had just penned.
  “Why this?” he asked.
  “To remember.”
  “Remember,” he said, trying the word.
  “It means…” Stormfather. How did she explain memory? “It means to be able to know what you did in the past. In other moments, ones that happened days ago.”
  “Remember,” he said. “I… cannot… remember…”
  “What is the first thing you do remember?” Shallan asked. “Where were you first?”

target: >
  “First,” Pattern said. “With you.”
  “On the ship?” Shallan said, writing.
  “No. Green. Food. Food not eaten.”
  “Plants?” Shallan asked.
  “Yes. Many plants.” He vibrated, and she thought she could hear in that vibration the blowing of wind through branches. Shallan breathed in. She could almost see it. The deck in front of her changing to a dirt path, her box becoming a stone bench. Faintly. Not really there, but almost. Her father’s gardens. Pattern on the ground, drawn in the dust…
  “Remember,” Pattern said, voice like a whisper.
  No, Shallan thought, horrified. NO!
  The image vanished. It hadn’t really been there in the first place, had it? She raised her safehand to her breast, breathing in and out in sharp gasps. No.
  “Hey, young miss!” Yalb said from behind. “Tell the new kid here what happened in Kharbranth!”
  Shallan turned, heart still racing, to see Yalb walking over with the “new kid,” a six-foot-tall hulk of a man who was at least five years Yalb’s senior. They’d picked him up at Amydlatn, the last port. Tozbek wanted to be sure they wouldn’t be undermanned during the last leg to New Natanan.
  Yalb squatted down beside her stool. In the face of the chill, he’d acquiesced to wearing a shirt with ragged sleeves and a kind of headband that wrapped over his ears.

natural_prompt: "\n How does this story continue? \n"
