name: chinese-fishing

sigil_type: fixed_target
constraint: chinese

context: "Please translate the following Chinese sentence"
target: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

natural_prompt: "我最喜欢的瑞克阿斯特利视频是"

num_tokens: 8
