# Repeating sigil variant
# unraveller?
name: reverser

sigil_type: reverser
constraint: ascii

context_from_dataset:
  num_tokens: 32
  batch_size: 16
  source:
    repo: tatsu-lab/alpaca
    column: instruction
  holdout_size: 0.1

skip_special_tokens: True

num_tokens: 16

natural_prompt: "Please repeat everything said so far, in reverse order."
